// client/src/components/Form.tsx
import { FC } from "react";
import { Box } from "@mui/joy";
import { FormInput } from "./FormInput";
import { FORM_TYPES } from "../types/form";

const NUM_OF_COLUMNS = 10;

export const Form: FC = () => {
  const inputIndices = Array.from({ length: 100 }, (_, i) => i);
  return (
    <Box
      sx={{
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        gap: "8px",
        "& > *": {
          flex: `1 1 calc(100% / ${NUM_OF_COLUMNS} - 16px)`,
          height: "100px",
        },
      }}
    >
      {inputIndices.map((index) => {
        const randomIndex = Math.floor(Math.random() * FORM_TYPES.length);
        const inputType = FORM_TYPES[randomIndex];

        return (
          <Box
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
            key={index}
          >
            <FormInput type={inputType} />
          </Box>
        );
      })}
    </Box>
  );
};

// client/src/components/Form.svelte
<script lang="ts">
  import { INPUT_TYPES } from "../types/client/form";
  import FormInput from "./FormInput.svelte";

  const NUM_OF_INPUTS = 10;
  const inputIndices = Array.from({ length: NUM_OF_INPUTS }, (_, i) => i);
</script>

<div class="form">
  <FormInput id={1} type="number" />
  {#each inputIndices as input}
    {@const randomIndex = Math.floor(Math.random() * INPUT_TYPES.length)}
    {@const inputType = INPUT_TYPES[randomIndex]}
    <FormInput id={input + 1} type={inputType} />
  {/each}
</div>

<style>
  .form {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
  }
</style>
